# Task2: Try Linear regression on same prediction data using Tensorflow

In [ ]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                    [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                    [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [4]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("Targets :\n",targets)

Targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [5]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(f"{v}\n{r}")

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.94273587, 0.76310277],
       [0.55373182, 0.36310367],
       [0.51283964, 0.7903987 ]])>
<tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([-0.73887268, -2.42044147])>


In [6]:
def model(s):
    return s @ v + r

In [7]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[127.23298233 111.60115033]
 [166.6002287  149.56054987]
 [185.22391114 158.46851536]
 [138.20572094 120.27425027]
 [153.36693203 140.41951059]
 [127.23298233 111.60115033]
 [166.6002287  149.56054987]
 [185.22391114 158.46851536]
 [138.20572094 120.27425027]
 [153.36693203 140.41951059]
 [127.23298233 111.60115033]
 [166.6002287  149.56054987]
 [185.22391114 158.46851536]
 [138.20572094 120.27425027]
 [153.36693203 140.41951059]], shape=(15, 2), dtype=float64)


In [8]:
def mean_square_error(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mean_square_error(prediction,targets))

tf.Tensor(4495.856493258744, shape=(), dtype=float64)


In [9]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mean_square_error(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 4495.856493258744
 
 Epoch count: 1 
 Loss value: 3025.7690230864946
 
 Epoch count: 2 
 Loss value: 2080.238175207914
 
 Epoch count: 3 
 Loss value: 1466.0335799391505
 
 Epoch count: 4 
 Loss value: 1061.8828657827646
 
 Epoch count: 5 
 Loss value: 791.5779159165785
 
 Epoch count: 6 
 Loss value: 607.1444090566125
 
 Epoch count: 7 
 Loss value: 478.3076270963227
 
 Epoch count: 8 
 Loss value: 385.8978105623959
 
 Epoch count: 9 
 Loss value: 317.7206308679387
 
 Epoch count: 10 
 Loss value: 265.97031359200105
 
 Epoch count: 11 
 Loss value: 225.60826255350293
 
 Epoch count: 12 
 Loss value: 193.3460697414948
 
 Epoch count: 13 
 Loss value: 167.0069533627022
 
 Epoch count: 14 
 Loss value: 145.12422567170532
 
 Epoch count: 15 
 Loss value: 126.68829718921263
 
 Epoch count: 16 
 Loss value: 110.98682534521859
 
 Epoch count: 17 
 Loss value: 97.50332749061043
 
 Epoch count: 18 
 Loss value: 85.85253882656768
 
 Epoch count: 19 
 Loss value: 